#!/bin/sh

DIR="$HOME/.dotfiles/shells"

if [ -z "$1" ]; then
  echo "Please provide a shell"
  exit 0
fi

if [ ! -d "$DIR/$1" ]; then
  echo "Provided shell not found"
  exit 0
fi

if [ ! -d "$DIR/$2" ]; then
  echo "Second provided shell not found"
  exit 0
fi

if [ -f ".envrc" ]; then
  echo "envrc already exists"
  exit 0
fi

cp "$DIR/$1/.envrc" .
line1="use flake $DIR/$1"
sed -i "1s|.*|$line1|" .envrc

tail -n +2 "$DIR/$2/.envrc" >> .envrc
line2="use flake $DIR/$2"
sed -i "2s|.*|$line2\n|" .envrc

direnv allow

echo "
.envrc
.direnv
" >> .git/info/exclude

echo "direnv is now configured with $1 shell"
exit 1
