#!/bin/sh

variant=$1

if [ -z "$WAYLAND_DISPLAY" ]; then
  if [ "$variant" = "intl" ]; then
    setxkbmap -layout us -variant intl
  else
    setxkbmap -layout us
  fi
else
  if niri -h >/dev/null 2>&1; then
    if [ "$variant" = "intl" ]; then
      niri msg action switch-layout 1
    else
      niri msg action switch-layout 0
    fi
  elif [ "$SWAY_SOCKET" ]; then
    if [ "$variant" = "intl" ]; then
      swaymsg input type:keyboard xkb_variant intl
    else
      swaymsg input type:keyboard xkb_variant '""'
    fi
  else
    if [ "$variant" = "intl" ]; then
      hyprctl keyword input:kb_variant intl
    else
      hyprctl reload
    fi
  fi
fi

if [ "$variant" = "intl" ]; then
  notify-send "switched to US International keyboard layout"
else
  notify-send "switched to US keyboard layout"
fi
