#!/bin/sh

if [ -z "$2" ]; then
  echo "Usage: $1 [playlist|audio|video]"
  exit 1
fi

case $2 in
  'playlist')
    echo "Downloading playlist..."
    youtube-dl -i -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --yes-playlist --embed-thumbnail --add-metadata --output '%(title)s.%(ext)s'
  ;;
  'audio')
    echo "Downloading audio..."
    youtube-dl -i -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --no-playlist --embed-thumbnail --add-metadata --output '%(title)s.%(ext)s'
  ;;
  'video')
    echo "Downloading video..."
    youtube-dl -i -f bestvideo --format mp4 --no-playlist --embed-thumbnail --add-metadata --output '%(title)s.%(ext)s'
  ;;
  *)
    echo "Usage: $2 [playlist|audio|video]"
    exit 1
  ;;
esac
